# Laboratorio II - Análisis de Discriminante y Regresión Logística

In [319]:
import numpy as np
import pandas as pd

## Base Pokémon

In [320]:
pokemon = pd.read_csv('pokemon.csv')

In [321]:
pokemon.shape

(801, 41)

In [322]:
pokemon.head()

abilities  against_bug  against_dark  against_dragon  \
0  ['Overgrow', 'Chlorophyll']          1.0           1.0             1.0   
1  ['Overgrow', 'Chlorophyll']          1.0           1.0             1.0   
2  ['Overgrow', 'Chlorophyll']          1.0           1.0             1.0   
3     ['Blaze', 'Solar Power']          0.5           1.0             1.0   
4     ['Blaze', 'Solar Power']          0.5           1.0             1.0   

   against_electric  against_fairy  against_fight  against_fire  \
0               0.5            0.5            0.5           2.0   
1               0.5            0.5            0.5           2.0   
2               0.5            0.5            0.5           2.0   
3               1.0            0.5            1.0           0.5   
4               1.0            0.5            1.0           0.5   

   against_flying  against_ghost  ...  percentage_male  pokedex_number  \
0             2.0            1.0  ...             88.1               1   
1             2.0            1.0  ...             88.1               2   
2             2.0            1.0  ...             88.1               3   
3             1.0            1.0  ...             88.1               4   
4             1.0            1.0  ...             88.1               5   

   sp_attack  sp_defense  speed  type1   type2  weight_kg  generation  \
0         65          65     45  grass  poison        6.9           1   
1         80          80     60  grass  poison       13.0           1   
2        122         120     80  grass  poison      100.0           1   
3         60          50     65   fire     NaN        8.5           1   
4         80          65     80   fire     NaN       19.0           1   

   is_legendary  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 41 columns]

Se utilizarán sólo los pokémon que tengan un solo tipo.

In [323]:
pokemon_df = pokemon[(pokemon["type2"].isnull()) | (pokemon["type1"] == pokemon["type2"])]
pokemon_df.shape

(391, 41)

Se seleccionan los features que se considerarán en el modelo.

In [324]:
features = [
    "sp_attack",
    "sp_defense",
    "attack",
    "defense",
    "speed",
    "hp",
    "type1"
]
pokemon_df = pokemon_df[features]
pokemon_df.shape

(391, 7)

In [325]:
pokemon_df["type1"].value_counts()

normal      61
water       61
grass       38
psychic     35
fire        28
electric    27
fighting    22
bug         18
fairy       16
poison      15
ground      12
dragon      12
ice         12
rock        11
dark         9
ghost        9
steel        4
flying       1
Name: type1, dtype: int64

Comparación de valores entre tipo *roca* y *hierba*.

In [326]:
feature_means1 = pd.DataFrame(columns=pokemon_df["type1"].drop_duplicates())
for c, rows in pokemon_df.groupby('type1'):
    feature_means1[c] = rows.mean()
# feature_means1
feature_means1[["rock", "grass"]]

/var/folders/vg/rrvy5r0s275_mqld96rv7s9r0000gn/T/ipykernel_80204/3283892196.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  feature_means1[c] = rows.mean()


type1             rock      grass
sp_attack    40.909091  71.815789
sp_defense   58.181818  63.842105
attack      100.909091  69.710526
defense      98.181818  68.894737
speed        39.818182  61.447368
hp           66.727273  63.184211

In [327]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import classification_report, confusion_matrix

In [338]:
X = pokemon_df.drop(["type1"], axis = 1)
y = pokemon_df["type1"]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

In [339]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1, test_size = 0.3)
lda_model = LinearDiscriminantAnalysis()
lda_model.fit(X_train, y_train)

LinearDiscriminantAnalysis()

In [341]:
pred_train = lda_model.predict(X_train)

In [343]:
print(confusion_matrix(y_train, pred_train))

[[ 2  0  0  1  0  0  0  0  0  0  1  0  3  0  0  0  0  4]
 [ 0  0  0  1  0  0  1  0  0  0  0  0  1  0  0  0  0  2]
 [ 0  0  0  0  2  4  0  0  0  0  0  0  0  0  0  0  0  4]
 [ 0  0  0  8  0  0  1  0  0  0  0  0  4  0  0  0  0  4]
 [ 0  0  0  0  4  0  0  0  0  0  0  0  2  0  3  0  0  5]
 [ 0  0  0  0  0 12  1  0  0  0  0  0  6  0  0  0  0  1]
 [ 0  0  1  0  0  1  3  0  0  0  0  0  4  0  1  0  0 11]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  2  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  2  1  1  2  0  0  0  1  0  2  0  1  0  0 15]
 [ 0  0  0  0  0  2  0  0  0  0  2  0  2  0  0  1  0  1]
 [ 0  0  0  0  1  0  1  0  1  0  1  0  0  0  0  0  0  3]
 [ 0  0  0  0  0  6  0  0  0  0  0  0 29  0  2  0  0 11]
 [ 0  0  0  0  0  0  1  0  0  0  0  0  6  0  0  0  0  3]
 [ 0  0  0  2  1  0  1  0  1  0  0  0  3  0  7  0  0  3]
 [ 0  0  0  0  0  3  0  0  0  0  0  0  0  0  0  3  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  1  0  0  0  0  1  0

In [344]:
print(classification_report(y_train, pred_train))

              precision    recall  f1-score   support

         bug       0.67      0.18      0.29        11
        dark       0.00      0.00      0.00         5
      dragon       0.00      0.00      0.00        10
    electric       0.47      0.47      0.47        17
       fairy       0.44      0.29      0.35        14
    fighting       0.41      0.60      0.49        20
        fire       0.27      0.14      0.19        21
      flying       0.00      0.00      0.00         1
       ghost       0.40      0.40      0.40         5
       grass       0.00      0.00      0.00        25
      ground       0.40      0.25      0.31         8
         ice       0.00      0.00      0.00         7
      normal       0.42      0.60      0.50        48
      poison       0.00      0.00      0.00        10
     psychic       0.41      0.39      0.40        18
        rock       0.60      0.43      0.50         7
       steel       0.00      0.00      0.00         1
       water       0.31    

/Users/matthiascleinespinoza/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/matthiascleinespinoza/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/matthiascleinespinoza/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modif

In [345]:
pred_test = lda_model.predict(X_test)

In [347]:
print(confusion_matrix(y_test, predicted))

[[ 2  0  0  0  0  1  0  0  0  0  0  0  1  0  0  0  0  3]
 [ 0  0  0  0  0  0  1  0  0  0  0  0  1  0  1  0  0  1]
 [ 0  0  0  0  1  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0  0  2  0  0  5]
 [ 0  0  0  0  1  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  1]
 [ 0  0  0  0  0  0  1  0  0  0  1  0  0  0  0  0  0  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  1  0  0  0  0  0  1  0  0  1]
 [ 0  0  0  1  0  0  0  0  0  0  1  0  1  0  0  0  0 10]
 [ 0  0  0  1  0  3  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  1  1  0  2]
 [ 0  0  0  0  0  3  0  0  1  0  0  0  6  0  1  0  0  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  4]
 [ 0  0  0  1  2  0  0  1  1  0  0  0  1  0  5  0  0  6]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  1  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  1  1  0  1  0  1  0

In [348]:
print(classification_report(y_test, predicted))

              precision    recall  f1-score   support

         bug       1.00      0.29      0.44         7
        dark       0.00      0.00      0.00         4
      dragon       0.00      0.00      0.00         2
    electric       0.43      0.30      0.35        10
       fairy       0.20      0.50      0.29         2
    fighting       0.00      0.00      0.00         2
        fire       0.33      0.14      0.20         7
      flying       0.00      0.00      0.00         0
       ghost       0.20      0.25      0.22         4
       grass       0.00      0.00      0.00        13
      ground       0.00      0.00      0.00         4
         ice       0.00      0.00      0.00         5
      normal       0.33      0.46      0.39        13
      poison       0.00      0.00      0.00         5
     psychic       0.36      0.29      0.32        17
        rock       0.50      0.50      0.50         4
       steel       0.00      0.00      0.00         3
       water       0.07    

/Users/matthiascleinespinoza/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/matthiascleinespinoza/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/matthiascleinespinoza/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg

In [350]:
pokemon_test = {
    "sp_attack": 75.3,
    "sp_defense": 51,
    "attack": 63,
    "defense": 47,
    "speed": 97,
    "hp": 66
}

pokemon_test = pd.Series(pokemon_test)
pokemon_test = scaler.transform([pokemon_test])
lda_model.predict(pokemon_test)

/Users/matthiascleinespinoza/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array(['water'], dtype='<U8')

## Base Breast Cancer

In [4]:
from sklearn.datasets import load_breast_cancer

In [5]:
breast_cancer = load_breast_cancer()
data = breast_cancer.data
target = breast_cancer.target
cols = breast_cancer.feature_names

In [6]:
breast_cancer_df = pd.DataFrame(data = data, columns = cols)
breast_cancer_df["target"] = target

In [7]:
breast_cancer_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]